DROP TABLE IF EXISTS keys;

CREATE TABLE keys (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nodeID TEXT NOT NULL,
    pubKey TEXT NOT NULL
);